name: 'Test Rails - The Gnar Way'
description: 'Setup and run the tests for your Rails app'
runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Setup App Dependencies
      shell: bash
      run: bin/setup

    - name: Generate Assets
      shell: bash
      run: bin/rails assets:precompile

    - name: Run tests
      shell: bash
      run: bin/rspec
