---
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - '**/vendor/**/*'
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  PartialInstanceVariable:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/ArgumentAlignment:
        EnforcedStyle: with_fixed_indentation
        IndentationWidth: 2
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: true
        Max: 100
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Style/TrailingCommaInArguments:
        EnforcedStyleForMultiline: no_comma
      Style/TrailingCommaInHashLiteral:
        EnforcedStyleForMultiline: comma
      Lint/UselessAssignment:
        Enabled: true
      Rails/OutputSafety:
        Enabled: true
