name: Run Tests (Yarn)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Run Tests (Yarn)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        run: "yarn install --ignore-engines --ignore-scripts"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Run Tests
        run: yarn test

      - name: Code Cov
        uses: codecov/codecov-action@v2.1.0
